### ISSUE TITLE
Problems building the project under macOS 13.3

### ISSUE THREAD

**Issue by carlca** [tpbeldie/UFLVK-Emu#1]
Hello, 

Have you, or anyone, managed to get this project to build under macOS 13.3 (the latest version of macOS)?

I've downloaded and installed the `Dotnet for macOS v7` installer from https://dotnet.microsoft.com/en-us/download
Apparently one just needs to run `dotnet restore` followed by `dotnet build -c Release`.
This should invoke the Dotnet command line tools to perform the build.

I initially ran into problems because the installer I mentioned didn't set the paths accordingly, but I managed to get the tool to run with `/usr/local/share/dotnet/x64/dotnet restore` followed by `/usr/local/share/dotnet/x64/dotnet build -c Release`. 

The first command runs error-free, but the build command fails. The URL mentioned in the error message just points to the Windows version, while clicking the link from that page just leads to the installer I used...

This is the error I received...

![Screenshot 2023-04-01 at 15 12 26](https://user-images.githubusercontent.com/260612/229294342-33f46af8-f3ef-441e-afbf-2e83e92897f5.png)

Any ideas, any one?

**Comment by tpbeldie** [comment]
This project was built using NET Framework 4.6, which is an older windows exclusive framework that is compatible with most Windows builds, so it's accessible to older Windows variants that has it installed as well (7, Vista, 8, 8.1). Note, there is a difference between .NET Framework and simple .NET (previously known as .NET Core). .NET Framework was built to work exclusively on Windows operating systems. It's just a software framework with the sole purpose of designing Windows-based applications, so you won't be able to run it in any other OS, unfortunately. 

You are trying to install the app as a modern .NET app, the cross platform framework, which this application does not use, on a Mac OS system, which this application wasn't built for. Sadly, it is Windows exclusive at this moment. In the future, if enough demand, I will consider creating a cross platform variant. 

On the bright side, know that it's a fresh project, it barely has two days, there are lots of bugs to be fixed and lots of features to be implemented. You can tell the world about it and with enough attention and support from people and other developers, chances are high that UFLVK-Emu will become cross platform.

I apologize for the sad news.  Closed.

**Comment by carlca** [comment]
Thanks for the reply! To be honest, this was always going to be filed under nice to have/intriguing to look at, rather than essential to my workflow. Make sure that you update us on Discord with any news 😉
